spring:
  datasource:
    url: jdbc:mysql://10.1.41.49/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wiki
    password: U2FsdGVkX19SGJB8OEN6ZdaP
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 10.1.100.163
      port: 6379
      password: Ianmu0810
server:
  port: 8088
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
