spring:
  datasource:
    url: jdbc:mysql://121.36.221.156/wiki_dev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wiki_dev
    password: Ianmu_wiki_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 124.70.161.210
      port: 6379
      password: Ianmu0810

server:
  port: 8088
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    com:
      ianmu:
        wiki:
          mapper: trace
124:
  70:
    161:
      210: