spring:
  datasource:
    url: jdbc:mysql://rm-uf67phjjf1svyi19m3o.mysql.rds.aliyuncs.com/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wiki_prod
    password: Wiki_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
