spring:
  datasource:
    url: jdbc:mysql://rm-uf67phjjf1svyi19m3o.mysql.rds.aliyuncs.com/wiki_dev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wiki_dev
    password: Wiki_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    com:
      ianmu:
        wiki:
          mapper: trace
